lib/chat_web/router.ex
defmodule ChatWeb.Router do
  use ChatWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", ChatWeb do
    pipe_through :browser

    resources("/threads", ThreadController, only: [:index, :create]) do
      resources("/posts", PostController, only: [:index])
    end
  end

  # Other scopes may use custom stacks.
  # scope "/api", ChatWeb do
  #   pipe_through :api
  # end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser
      live_dashboard "/dashboard", metrics: ChatWeb.Telemetry
    end
  end
end

lib/chat/application.ex
defmodule Chat.Application do
  # See https://hexdocs.pm/elixir/Application.html
  # for more information on OTP Applications
  @moduledoc false

  use Application

  def start(_type, _args) do
    children = [
      # Start the Ecto repository
      Chat.Repo,
      # Start the Telemetry supervisor
      ChatWeb.Telemetry,
      # Start the PubSub system
      {Phoenix.PubSub, name: Chat.PubSub},
      # Start the Endpoint (http/https)
      ChatWeb.Endpoint
      # Start a worker by calling: Chat.Worker.start_link(arg)
      # {Chat.Worker, arg}
    ]

    # See https://hexdocs.pm/elixir/Supervisor.html
    # for other strategies and supported options
    opts = [strategy: :one_for_one, name: Chat.Supervisor]
    Supervisor.start_link(children, opts)
  end

  # Tell Phoenix to update the endpoint configuration
  # whenever the application is updated.
  def config_change(changed, _new, removed) do
    ChatWeb.Endpoint.config_change(changed, removed)
    :ok
  end
end

lib/chat/board.ex
defmodule Chat.Board do
  import Ecto.Query, warn: false
  alias Chat.Repo
  alias Chat.Board.Post

  def list_posts(thread_id) do
    Post
    |> where([p], p.thread_id == ^thread_id)
    |> order_by([p], [asc: p.number])
    |> Repo.all
  end

  def get_next_post_number(thread_id) do
    Post
    |> select([p], p.number)
    |> where([p], p.thread_id == ^thread_id)
    |> order_by([p], [desc: p.number])
    |> limit([p], 1)
    |> Repo.one
    |> Kernel.||(0)
    |> Kernel.+(1)
  end

  def create_post!(%{thread_id: thread_id, body: body, name: ""}), do: create_post!(%{thread_id: thread_id, body: body, name: "名無しさん"})

  def create_post!(%{thread_id: thread_id, body: body, name: name}) do
    %Post{}
    |> Post.changeset(Map.put(%{ thread_id: thread_id, body: body, name: name }, :number, get_next_post_number(thread_id)))
    |> Repo.insert!()
  end
end

lib/chat/board/post.ex
defmodule Chat.Board.Post do
  use Ecto.Schema
  import Ecto.Changeset

  schema "posts" do
    field :thread_id, :integer
    field :name, :string
    field :body, :string
    field :number, :integer

    timestamps()
  end

  @spec changeset(
          {map, map}
          | %{
              :__struct__ => atom | %{:__changeset__ => map, optional(any) => any},
              optional(atom) => any
            },
          :invalid | %{optional(:__struct__) => none, optional(atom | binary) => any}
        ) :: Ecto.Changeset.t()
  def changeset(post, attrs) do
    post
    |> cast(attrs, [:thread_id, :name, :body, :number])
  end
end

lib/chat/repo.ex
defmodule Chat.Repo do
  use Ecto.Repo,
    otp_app: :chat,
    adapter: Ecto.Adapters.MyXQL
end

lib/chat/title.ex
defmodule Chat.Title do
  import Ecto.Query, warn: false
  alias Chat.Repo
  alias Chat.Title.Thread

  def list_threads do
    Thread
    |> order_by([p], [asc: p.id])
    |> Repo.all
  end

  def get_thread(thread_id) do
    Thread
    |> Repo.get!(thread_id)
  end

  def create_thread(%{title: title}) do
    %Thread{}
    |> Thread.changeset(%{ title: title })
    |> Repo.insert()
  end
end

lib/chat/title/thread.ex
defmodule Chat.Title.Thread do
  use Ecto.Schema
  import Ecto.Changeset

  schema "threads" do
    field :title, :string

    timestamps()
  end

  def changeset(thread, attrs) do
    thread
    |> cast(attrs, [:title])
    |> validate_required([:title])
  end
end

lib/chat_web/controllers/post_controller.ex
defmodule ChatWeb.PostController do
  use ChatWeb, :controller
  alias Chat.Board
  alias Chat.Title

  def index(conn, %{ "thread_id" => thread_id }) do
    thread = Title.get_thread(thread_id)
    posts = Board.list_posts(thread_id)
    render(conn, "index.html", posts: posts, thread: thread)
  end
end

lib/chat_web/controllers/thred_controller.ex
defmodule ChatWeb.ThreadController do
  use ChatWeb, :controller
  alias Chat.Title

  def index(conn, _params) do
    threads = Title.list_threads()
    render(conn, "index.html", threads: threads)
  end

  # def new(conn, _params) do
  #   thread = Title.build_thread
  #   changeset = Title.change_thread(thread)
  #   render(conn, "new.html", changeset: changeset)
  # end

  # def create(conn, %{ "thread" => thread_params }) do
  #   Title.create_thread(thread_params)
  #   redirect(conn, to: Routes.thread_path(conn, :index))
  # end
end

lib/chat_web/views/error_view.ex
defmodule ChatWeb.ErrorView do
  use ChatWeb, :view

  # If you want to customize a particular status code
  # for a certain format, you may uncomment below.
  # def render("500.html", _assigns) do
  #   "Internal Server Error"
  # end

  # By default, Phoenix returns the status message from
  # the template name. For example, "404.html" becomes
  # "Not Found".
  def template_not_found(template, _assigns) do
    Phoenix.Controller.status_message_from_template(template)
  end
end

lib/chat_web/views/layout_view.ex
defmodule ChatWeb.LayoutView do
  use ChatWeb, :view
end

lib/chat_web/views/post_view.ex
defmodule ChatWeb.PostView do
  use ChatWeb, :view
  alias Timex.Format.DateTime.Formatters.Strftime

  def format_datetime(time) do
    Strftime.format!(time, "%Y年%-m月%-d日 %H:%M:%S")
  end
end

lib/chat_web/views/thread_view.ex
defmodule ChatWeb.ThreadView do
  use ChatWeb, :view
end

lib/chat_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>Chat · Phoenix Framework</title>
    <link rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/app.css") %>"/>
    <script defer type="text/javascript" src="<%= Routes.static_path(@conn, "/js/app.js") %>"></script>
  </head>
  <body>
    <header>
      <section class="container">
        <nav role="navigation">
          <ul>
            <li><a href="https://hexdocs.pm/phoenix/overview.html">Get Started</a></li>
            <%= if function_exported?(Routes, :live_dashboard_path, 2) do %>
              <li><%= link "LiveDashboard", to: Routes.live_dashboard_path(@conn, :home) %></li>
            <% end %>
          </ul>
        </nav>
        <a href="https://phoenixframework.org/" class="phx-logo">
          <img src="<%= Routes.static_path(@conn, "/images/phoenix.png") %>" alt="Phoenix Framework Logo"/>
        </a>
      </section>
    </header>
    <main role="main" class="container">
      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>
      <%= @inner_content %>
    </main>
  </body>
</html>

lib/chat_web/templates/post/index.html.eex
<h1><%= @thread.title %></h1>
<ul id="messages">
  <%= for post <- @posts do %>
    <li>
      <%= "#{post.number} #{post.name} #{format_datetime(post.inserted_at)}" %>
      <br>
      <p>
        <%= for split_body <- String.split(post.body, "\n") do %>
          <%= split_body %>
          <br>
        <% end %>
      </p>
    </li>
  <% end %>
</ul>
<input type="hidden" id="thread-id" value="<%= @thread.id %>">
<input id="name-input">
<textarea id="chat-input"></textarea>
<input id="send-button" type="button" value="送信">

lib/chat_web/templates/thread/index.html.eex
<ul>
  <%= for thread <- @threads do %>
    <li><%= link thread.title, to: Routes.thread_post_path(@conn, :index, thread.id) %></li>
  <% end %>
</ul>